### ISSUE TITLE
Update bot

### ISSUE THREAD

**Issue by fanatikvoice** [Halreis/Discord-SourceQuery#3] opened 2017-09-19 17:34 UTC
Hello, in the bot
I saw flaw - If you add it to the crowns, it makes a copy of the program. Can I add a label indicating that it is running.

**Comment by Halreis** [comment] 2017-09-19 19:23
I kinda don’t seem to get it.

* What is crowns?
* Where are you trying to assign it to those crowns (or crowns to the bot)?
* What’s up with the label? — you can use `ps -f -C python3 | grep 'bot.py'` to check whether it is running or not.

**Comment by fanatikvoice** [comment] 2017-09-19 19:41
1. Cron: https://en.wikipedia.org/wiki/Cron
2. I add task in Cron (Dedicated Server) - time task in cron.
3. Thx

And how to prevent the creation of copy of the programm? What should be done?
Whether it is possible to finish program - when `/check` shows server - there was a name of server

**Comment by Halreis** [comment] 2017-09-19 21:07
Ah, I see now.

>And how to prevent the creation of copy of the programm? What should be done?

Well, you don’t have to add it to the crontab. Just `python3 bot.py` it and it enters an endless loop, pretty much. If you _really_ need it to be constantly restarted, you could use a bash script (`pgrep` could also do) or a python-based PID file r/w algo.

>Whether it is possible to finish program - when /check shows server - there was a name of server

Just call `sys.exit()` after the whole stack is done.

**Comment by fanatikvoice** [comment] 2017-09-20 14:41
>Just call sys.exit(), exit() or quit() after the whole stack is finished.
Sorry, bad my english. I mean https://pp.userapi.com/c837130/v837130244/57948/TLXIJK0h7G0.jpg -> Remove double messages. 
And so that the name of the server is displayed -> https://pp.userapi.com/c837130/v837130244/5795a/fKMe6J-mSL8.jpg

**Comment by Halreis** [comment] 2017-09-20 17:44
>Remove double messages.

Double messages aren’t a thing. It is likely that you’re running a bunch of bot instances, so they all respond and send multiple messages. [This is](https://my.mixtape.moe/prdkzg.png) the intended behaviour.

>And so that the name of the server is displayed

This command isn’t meant to show server details. You can use `/q[uery]` command to get complete server info.
Still, the example can be seen at lines 23-28. Then, line 73 contains the field name. Concatenate the resulting hostname with existing string and you're good to go. But I wouldn’t recommend doing this since field names have a certain size limit and server names combined with their full addresses could just not fit in (not to mention the screwed up grid).

**Comment by fanatikvoice** [comment] 2017-09-22 15:47
Say pls, how can add a new command to restart or exit? A short command - /ex or /rest
How it can be reloaded - it does not respond to commands in the terminal.

**Comment by Halreis** [comment] 2017-09-22 17:05
> how can add a new command to restart or exit? A short command - /ex or /rest

[This](https://discordpy.readthedocs.io/en/latest/faq.html#commands-extension) should help.

> How it can be reloaded - it does not respond to commands in the terminal.

It sure won’t respond to your lines since pyton interpreter isn’t listening. You have to add one of those three calls to a function’s tail in order to execute them.

**Comment by fanatikvoice** [comment] 2017-09-22 18:31
> This should help.

> 
I dont understand. I not install this is.

> How to in command /check change IP-Server on Name Server (Name is from command /q)

>
As you wrote above - I could not change the IP of the server on line 75 on the Server name

**Comment by Halreis** [comment] 2017-09-22 19:01
In order to implement those things, you gotta have some basic python skills.
Besides, I can’t help you if you’re not going to follow the installation/usage guide properly.

I’m closing this issue for now.

**Closed by Halreis** 2017-09-22 19:01 UTC
